apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pr-mynginx-13
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: previews
  source:
    path: yamls
    repoURL: https://github.com/nexcollab-bot/mynginx.git
    targetRevision: HEAD
    helm:
      values: |
        image: 
          tag: v13
        ingress:
          host: pr-mynginx-13.165.232.98.105.xip.io
      version: v3
  destination:
    namespace: pr-mynginx-13
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
